# Copyright 2016, JinkIT, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: bootstrap | check if bootstrap is needed
  raw: which python
  register: need_bootstrap
  ignore_errors: True

- name: bootstrap | install python 2.x
  raw: yum install -y centos-release-SCL python-minimal
  when: need_bootstrap | failed

- set_fact:
    ansible_python_interpreter: "/usr/bin/python"

- name: upgrade the entire system in preparation for next steps
  yum: name=* state=latest

# - name: setup elrepo gpgkey
#   shell: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
#
# - name: adding elrepo kernel repo
#   template:
#     src: templates/elrepo-kernel.repo.j2
#     dest: /etc/yum.repos.d/elrepo-kernel.repo
#     backup: no
#     owner: root
#     group: root
#
# - name: updating kernel
#   shell: yum install -y kernel-ml && grub2-set-default 0
#
# - name: disabling ipv6
#   shell: echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf && echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf

- name: installing epel
  shell: yum install -y epel-release

- name: installing ceph repo
  yum: name=http://download.ceph.com/rpm-jewel/el7/noarch/ceph-release-1-1.el7.noarch.rpm state=present

- name: installing ceph
  shell: yum install -y ceph

# - name: restart machine
#   shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#   async: 1
#   poll: 0
#   sudo: true
#   ignore_errors: true
#
# - name: waiting for server to come back
#   local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
